# Output directory is absolute path OR
#  is specified relative to current working directory
output = "scratch"
user-sub-file = "DiCDM.for"

[compile]
include = ['cohFaliure.for']
# fflags = "-qopenmp"


[[job]]
job-file = "Transverse-Tension-singleply.inp"
tags = "default"
name = "Transverse Tension Single Ply"
