name: Test

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: '2.x'
    
    - name: Check version
      run: python --version

    - name: Setup git config
      run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "<>"

    - name: Run Tests
      run: python test/test_runner.py

    - name: Install coverage.py
      run: |
        pip install coverage
        coverage --version

    - name: Run Coverage
      run: |
        coverage run --source=src test/test_runner.py
        coverage report
